# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    workingDirectory: "Manifest Parser"
    displayName: "Build Manifest Parser - $(buildConfiguration)"

  - script: dotnet test
    workingDirectory: "Manifest Parser.Tests"
    displayName: "Run unit tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "VSTest"
      testResultsFiles: "$(System.DefaultWorkingDirectory)/Manifest Parser.Tests/UnitTestResults/*.trx"
      searchFolder: "Manifest Parser.Tests/UnitTestResults"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "Manifest Parser/bin/Debug"
      contents: "**.nupkg"
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
      publishLocation: "Container" # Options: container, filePath
