# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    workingDirectory: "Manifest Parser"
    displayName: "Build Manifest Parser - $(buildConfiguration)"

  - script: dotnet test
    workingDirectory: "Manifest Parser.Tests"
    displayName: "Run unit tests"

  # Publish Test Results to Azure Pipelines/TFS
  - task: PublishTestResults@2
    inputs:
      searchFolder: 'Manifest Parser.Tests\UnitTestResults'
